### PR TITLE
Replace extract-pot with gulp-based pipeline

### LINKED ISSUE #423: extract-pot does not recognize format()
For example `templates/country/dataset.html` has

    <p>{{format("On this page you can see the state of open data for %(dataset)s in all the places for which we have information.", { dataset: dataset.title}) }}</p>

This can't be localized as it's never in the po template.

### PR DESCRIPTION
**Pull request by clkao**
Fixes #423.

This does bring in additional dependencies, but they are dev-only, and only used when updating the po template.

Ideally we'll be able to manage the vendor assets with bower via gulp in the future.

### CODE REVIEW

**Comment by clkao** [comment]
@rgrp any thought on this one?

**Comment by pwalsh** [comment]
Hi @clkao I can't speak for @rgrp, but I would like to merge this. If you don't mind, can you replace the LiveScript with js, and possibly wrap all the trans commands with gulp (so we have a consistent interface). I'll then find some time in the coming week to check the changes and ok a merge.

**Comment by clkao** [comment]
@pwalsh please see the updated PR ;)

**Comment by pwalsh** [comment]
Ok thanks.

**Pull request merged**
