### PR TITLE
survey flow diagram

### PR DESCRIPTION
**Pull request by mintcanary**

### CODE REVIEW

**Comment by morchickit** [comment]
@mintcanary - you amazing person! However, where does it saves it to (meaning, where will it present it?)

**Comment by mintcanary** [comment]
As is, it'll be at global.census.okfn.org/survey-flow.html

**Comment by pwalsh** [comment]
@morchickit @mintcanary 

Should this not be with the other documentation on the gh-pages branch? I don't like including this in the main code branch, away from other docs.

**Comment by mintcanary** [comment]
That sounds sensible to me @pwalsh I just put it here for want of a better place. @morchickit will know more about how this will be used however.

**Comment by pwalsh** [comment]
@mintcanary ok, no problem. @morchickit can we move it to the docs branch?

**Comment by morchickit** [comment]
Yes please!

**Comment by pwalsh** [comment]
@mintcanary @morchickit 

now in docs:

http://census.okfn.org/survey-flow/

Linked from:

http://census.okfn.org/

This PR dies :).

**Pull request closed without merging**
