### PR TITLE
Initial work for #424, showing empty entries in dataset view

### PR DESCRIPTION
**Pull request by clkao**

### CODE REVIEW

**Comment by pwalsh** [comment]
@clkao is this still relevant?

**Comment by clkao** [comment]
Yes, see http://local.data.g0v.tw/dataset/g0v:d63a0a9d-aba8-4fbc-8a04-437df055f2fc for example, this allows sharing specific dataset and ask people around the country to complete the survey for that specific dataset.
I forgot what's missing in the PR though.  I will take a look this weekend (and rebase).

**Comment by pwalsh** [comment]
ok.

**Comment by pwalsh** [comment]
Closing this, as it is quite stale and the codebase has changed significantly. Please open an issue to add this as a feature so we can discuss.

**Pull request closed without merging**
