### PR TITLE
Log stack trace for 500-level errors

### PR DESCRIPTION
**Pull request by longhotsummer**
This makes debugging these errors not impossible.

### CODE REVIEW

**Comment by pwalsh** [comment]
thanks!

**Comment by vlevit** [comment]
I believe it will not work in promises. Perhaps we need to replace all the catch handlers in promises with similar statement which would print the stack trace.

**Comment by pwalsh** [comment]
No, it won't work for promises. We could/should replace the use of `console.log.bind(console)` which we use in all catch handlers with a proper error handler. @vlevit can you open an issue for this, and assign to yourself :).

**Comment by longhotsummer** [comment]
Yes please! We've had a lot of trouble debugging issues where all we have is a type error for accessing an attribute on a null object and no idea where it happens.

There must be a best practice for error handling and logging in node.js, but I'm not familiar enough with it to know.

Greg
--
(iPhone)

**Pull request merged**
